import React from 'react';

import { Container } from '../../ui-atoms/Container/Container';

import { Welcome } from './Welcome';

const Home = () => (
  <div>
    <Welcome />
    <Container>
      Home
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ipsam quibusdam voluptate. Accusamus distinctio dolorem, officiis perspiciatis sed unde voluptate! Ad adipisci amet blanditiis cumque delectus, distinctio earum eius facere fuga itaque, laudantium libero magni minima perspiciatis provident sed velit voluptates. Accusantium adipisci aperiam at commodi consequuntur cupiditate eius error eum eveniet ex facilis incidunt labore laborum modi molestiae natus necessitatibus officia perspiciatis quaerat quasi qui quo rem rerum ut veritatis vitae, voluptates? Dignissimos explicabo facere fugiat nisi repellendus saepe. Ad architecto aut, cum cumque doloribus enim error esse facilis harum incidunt itaque maxime natus omnis, perspiciatis provident quasi quidem sapiente vel velit voluptates? Aliquid animi, delectus eligendi eos, id ipsum laborum nesciunt numquam possimus quaerat rem, repudiandae rerum saepe? Alias aliquam amet at atque blanditiis consequatur corporis debitis deleniti deserunt dolorem eligendi et facere fuga fugit harum in ipsa ipsum itaque laborum magni minus, molestiae, nam nemo numquam officia perspiciatis porro quibusdam quidem quis reiciendis soluta tenetur ullam unde, velit veritatis voluptas voluptate! Ad animi, architecto beatae dignissimos dolor dolores ea et magni mollitia nihil, nobis quam qui quibusdam quo tempora tenetur voluptatibus. Ad deserunt doloremque, doloribus excepturi nihil nostrum numquam officia omnis praesentium quidem? Ad assumenda aut, beatae commodi dignissimos dolorum eum facere ipsam itaque molestiae odio quasi rem tempore! Asperiores dignissimos eaque ex fugiat harum minus nisi numquam praesentium qui, quibusdam. Exercitationem, nam, rerum. Accusantium ad adipisci beatae distinctio eligendi hic iusto pariatur vitae voluptate! Accusamus, aspernatur blanditiis dicta dolorem est ipsum quia! Alias aliquam aspernatur beatae consequatur cum delectus dicta dignissimos, esse facere ipsa laboriosam laudantium libero maxime natus nostrum porro quia, quibusdam quos repellendus reprehenderit sed soluta sunt ullam vel vitae. Aliquam animi at deserunt earum, et ex excepturi facilis impedit iure magnam nam necessitatibus, nobis odio quasi quis, quod rerum similique sit voluptas voluptatibus.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid autem cum delectus dignissimos distinctio dolor dolores, dolorum eaque eligendi enim eum expedita facilis fugit incidunt labore minima, natus necessitatibus nostrum numquam perferendis possimus praesentium quis recusandae repellendus similique soluta ullam vitae. Animi cumque cupiditate dolor ducimus eligendi eveniet incidunt velit? Architecto beatae cum iure obcaecati perferendis quam quo repellendus suscipit. Consectetur, dignissimos dolore dolorem exercitationem impedit nam nemo numquam quasi reprehenderit tempora? Accusantium ad adipisci atque corporis deleniti deserunt distinctio eligendi eveniet excepturi fugiat fugit illo labore magnam maxime minus molestias nam nemo nihil nulla numquam provident, quos similique sint tempore totam velit, voluptates voluptatum. Accusamus accusantium dolorem eaque explicabo facilis illo neque ullam. Amet aut, cum debitis, dolore doloribus ea eos esse ex explicabo, illum impedit laborum minima neque nesciunt nisi quam quas quasi quod rerum saepe sint unde voluptates. Ab, ad aliquam aliquid assumenda blanditiis consequatur, delectus eligendi est harum ipsum molestias officiis provident quod reiciendis sint? Dolore dolores eligendi nostrum optio quisquam tempora ullam vero. Amet consequuntur dicta officia provident quaerat quas quos tempora ut veritatis, voluptatibus. Alias consectetur cumque deserunt dolorum est illum incidunt inventore molestias, officiis velit. Accusamus, corporis dolores incidunt molestiae quis reiciendis similique. Ad cupiditate facere facilis fuga, itaque nesciunt nobis perspiciatis reprehenderit sapiente sequi tenetur unde voluptas voluptatibus. Aliquid aperiam atque dignissimos dolorum, exercitationem hic illo libero molestiae nisi perferendis quis ratione vitae? Aperiam asperiores assumenda ea eum eveniet hic id illo impedit ipsa iure labore magnam, nam necessitatibus nostrum odio perspiciatis, porro provident qui quia quibusdam repudiandae sit sunt suscipit, tenetur vitae voluptatibus voluptatum! Mollitia odit quaerat quasi quisquam quod. Corporis, eos libero! Amet asperiores, atque deleniti dignissimos, dolorum facilis itaque, laudantium officiis perspiciatis placeat quasi sapiente suscipit vel. Culpa cupiditate minima molestiae quibusdam! Aliquid est, harum id maiores rem vel?
    </Container>
  </div>
);

export default Home;
